debezium/dbz#2740 Add debezium-connect-plugins to Debezium Server distribution
Since the dist switched to the debezium-quarkus-* extensions, debezium-connect-plugins
is only resolved transitively via debezium-scripting, which is test scoped by default
and excluded from lib/ by the assembly. As a result all built-in SMTs fail with
ClassNotFoundException / NoClassDefFoundError on io.debezium.transforms.* classes.

Signed-off-by: maarten.vercruysse <maarten.vercruysse@outlook.be>

Signed-off-by: Maarten Vercruysse <67873169+MV-GH@users.noreply.github.com>