debezium/dbz#1185 Sink connector framework pt.2.2 - add shared sink connector framework for JDBC sink connector * Moving SchemaRegistryContainer and SchemaRegistryTestResourceLifecycleManager to Debezium Server repository * NoClassDefFoundError: io/strimzi/test/container/StrimziKafkaCluster$StrimziKafkaClusterBuilder in Debezium Server after update to StrimziKafkaCluster * fix sink metrics
relates to debezium/dbz#1185

Signed-off-by: rk3rn3r <1249289+rk3rn3r@users.noreply.github.com>